### ISSUE TITLE
Slight change in the CPSMS API

### ISSUE THREAD

**Issue by casper6060** [klinkby/klinkby.compaya#1]
Hi, i have been using this Wrapper for the CPSMS API and it helped me a lot, although i do feel i should mention that they changed to CPSMS API a little (as far as i know) so that you have to go in and and set CPSMS to only send to Danish numbers, if not done, the method will not accept a number with 45 preppended to it, so you will either have to set this up in the CPSMS admin panel or if not, you will have to open up the .cs file and change the int Receiver to a long Receiver thereby allowing you to enter 10 digits rather than the normal 8 :)

**Comment by klinkby** [comment]
Hi Casper, I'm glad you like it. And thank you for noticing this change.
Per your suggestion I have changed the int to long to cater for international numbers.
